version: "3.8"

services:
  n8n:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    container_name: n8n_codespace
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./data:/home/node/.n8n
      - ./data/workflows:/home/node/.n8n/workflows  # Adicionando mapeamento para a pasta workflows
